#Created by webjeda - http://webjeda.com

title: Chin-Yi #Keep it short
email: chinyihcy@email.com

baseurl: /chinyihu

sass:
 style: compressed
 
 
# Tracker
analytics: UA-83979019-1
 
### exclude the instructions / write-up in the README.md
exclude:
- README.md
